apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-cluster-roles
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["create", "get", "list", "update", "delete"]

